#!/bin/bash

if [ '$1' == "--help" ] || [ '$1' == "-h" ]; then
    echo "Usage: ./tp [player] <location>"
    exit 0
fi

# global
CFG_PATH="./tp.cfg"

# read cfg
source $CFG_PATH

# default
if [ $# -eq 1 ]; then 
    player=$default_player
    location=$1
elif [ $# -eq 2 ]; then
    player=$1
    location=$2
elif [ $# -eq 0 ]; then
    echo "[ERROR] at least one argument required."
else
    echo "[ERROR] too many argument."
fi

xyz=${locations[$location]}


# read targets
targets=(${xyz//,/ })

command="/tp $player ${targets[0]} ${targets[1]} ${targets[2]}\n"
screen -r $screen_session_name -X stuff "$command"

echo "tp $player to $location (${locations[$location]})"
